#!/bin/bash


if [[ $# -ne 1 ]]; then
  echo "Please push 1 and only 1 task"
  exit
fi

PUSHPOPDATABASE=${PUSHPOPT:=$HOME/pushpopdb.txt}
if [[ ! -f $PUSHPOPDATABASE ]] ; then
  echo "Creating new pushpop dabtabase at $PUSHPOPDATABASE"
  mkdir -p "${PUSHPOPDATABASE%/*}" && touch "$PUSHPOPDATABASE"
fi

echo $1 >> $PUSHPOPDATABASE



